# Generated by Django 4.2.9 on 2024-04-15 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="University",
            fields=[
                ("university_id", models.AutoField(primary_key=True, serialize=False)),
                ("university_name", models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.CharField(blank=True, max_length=50, null=True)),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("phone_num", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "expected_graduation",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "present_college",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "present_major",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "current_standing",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "host_contact_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "host_contact_email",
                    models.EmailField(blank=True, max_length=50, null=True),
                ),
                (
                    "university",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.university",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.PositiveIntegerField(
                        choices=[
                            (0, "Architecture"),
                            (1, "Art and Design"),
                            (2, "Arabic and Translation Studies"),
                            (3, "Biology, Chemistry and Environmental Sciences"),
                            (4, "English"),
                            (5, "International Studies"),
                            (6, "Media Communication"),
                            (7, "Mathematics and Statistics"),
                            (8, "Physics"),
                            (9, "Psychology"),
                            (10, "Chemical and Biological Engineering"),
                            (11, "Civil Engineering"),
                            (12, "Computer Science and Engineering"),
                            (13, "Electrical Engineering"),
                            (14, "Industrial Engineering"),
                            (15, "Mechanical Engineering"),
                            (16, "Accounting"),
                            (17, "Economics"),
                            (18, "Finance"),
                            (19, "Management, Strategy and Entrepreneurship"),
                            (20, "Marketing and Information Systems"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "faculty_type",
                    models.PositiveIntegerField(
                        choices=[
                            (0, "Admin_Assistant"),
                            (1, "Teaching_Faculty"),
                            (2, "Head_of_Department"),
                            (3, "Advisor"),
                            (4, "Associate_Dean"),
                            (5, "Scholarship"),
                            (6, "Sponsorship"),
                            (7, "IXO"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseApplication",
            fields=[
                (
                    "course_application_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("course_code", models.CharField(blank=True, max_length=50)),
                ("course_title", models.CharField(blank=True, max_length=50)),
                ("course_credits", models.IntegerField(default=0)),
                ("aus_course", models.CharField(blank=True, max_length=50)),
                ("syllabus", models.CharField(blank=True, max_length=50)),
                ("aus_syllabus", models.CharField(blank=True, max_length=50)),
                ("program_area", models.CharField(blank=True, max_length=50)),
                ("grade_required", models.CharField(blank=True, max_length=50)),
                ("pre_requisites_met", models.BooleanField(default=False)),
                ("approved_status", models.BooleanField(default=False)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.student"
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.university",
                    ),
                ),
            ],
        ),
    ]
