# Generated by Django 4.2.9 on 2024-04-26 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IXODetails",
            fields=[
                (
                    "initial_approval_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("moe_approval", models.BooleanField(blank=True, null=True)),
                ("usdoe_approval", models.BooleanField(blank=True, null=True)),
                ("acreditted", models.BooleanField(blank=True, null=True)),
                ("acreditted_comments", models.TextField(blank=True, null=True)),
                ("agreement", models.BooleanField(blank=True, null=True)),
                ("initial_approval_date", models.DateField(blank=True, null=True)),
                (
                    "student_type",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("advisor_approval", models.BooleanField(blank=True, null=True)),
                ("advisor_approval_date", models.DateField(blank=True, null=True)),
                ("associate_dean_approval", models.BooleanField(blank=True, null=True)),
                (
                    "associate_dean_approval_date",
                    models.DateField(blank=True, null=True),
                ),
                ("scholarship_approval", models.BooleanField(blank=True, null=True)),
                ("scholarship_approval_date", models.DateField(blank=True, null=True)),
                ("sponsorship_approval", models.BooleanField(blank=True, null=True)),
                ("sponsorship_approval_date", models.DateField(blank=True, null=True)),
                ("ixo_approval", models.BooleanField(blank=True, null=True)),
                ("ixo_approval_date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="University",
            fields=[
                ("university_id", models.AutoField(primary_key=True, serialize=False)),
                ("university_name", models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("aus_id", models.CharField(blank=True, max_length=250, null=True)),
                ("name", models.CharField(blank=True, max_length=250, null=True)),
                ("phone_num", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "expected_graduation",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "present_college",
                    models.PositiveIntegerField(
                        choices=[
                            (0, "Unknown"),
                            (1, "CAAD"),
                            (2, "CAS"),
                            (3, "CEN"),
                            (4, "SBA"),
                        ],
                        default=0,
                        null=True,
                    ),
                ),
                (
                    "present_major",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "department",
                    models.IntegerField(
                        choices=[
                            (0, "Unknown"),
                            (1, "Architecture"),
                            (2, "Art and Design"),
                            (3, "Arabic and Translation Studies"),
                            (4, "Biology, Chemistry and Environmental Sciences"),
                            (5, "English"),
                            (6, "International Studies"),
                            (7, "Media Communication"),
                            (8, "Mathematics and Statistics"),
                            (9, "Physics"),
                            (10, "Psychology"),
                            (11, "Chemical and Biological Engineering"),
                            (12, "Civil Engineering"),
                            (13, "Computer Science and Engineering"),
                            (14, "Electrical Engineering"),
                            (15, "Industrial Engineering"),
                            (16, "Mechanical Engineering"),
                            (17, "Accounting"),
                            (18, "Economics"),
                            (19, "Finance"),
                            (20, "Management, Strategy and Entrepreneurship"),
                            (21, "Marketing and Information Systems"),
                        ],
                        default=0,
                        null=True,
                    ),
                ),
                (
                    "current_standing",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "host_contact_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "host_contact_email",
                    models.EmailField(blank=True, max_length=250, null=True),
                ),
                ("submitted_form", models.BooleanField(default=False)),
                (
                    "ixo_details",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.ixodetails",
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.university",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["aus_id"],
            },
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.PositiveIntegerField(
                        choices=[
                            (0, "Unknown"),
                            (1, "Architecture"),
                            (2, "Art and Design"),
                            (3, "Arabic and Translation Studies"),
                            (4, "Biology, Chemistry and Environmental Sciences"),
                            (5, "English"),
                            (6, "International Studies"),
                            (7, "Media Communication"),
                            (8, "Mathematics and Statistics"),
                            (9, "Physics"),
                            (10, "Psychology"),
                            (11, "Chemical and Biological Engineering"),
                            (12, "Civil Engineering"),
                            (13, "Computer Science and Engineering"),
                            (14, "Electrical Engineering"),
                            (15, "Industrial Engineering"),
                            (16, "Mechanical Engineering"),
                            (17, "Accounting"),
                            (18, "Economics"),
                            (19, "Finance"),
                            (20, "Management, Strategy and Entrepreneurship"),
                            (21, "Marketing and Information Systems"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "college",
                    models.PositiveIntegerField(
                        choices=[
                            (0, "Unknown"),
                            (1, "CAAD"),
                            (2, "CAS"),
                            (3, "CEN"),
                            (4, "SBA"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "faculty_type",
                    models.PositiveIntegerField(
                        choices=[
                            (0, "Admin_Assistant"),
                            (1, "Teaching_Faculty"),
                            (2, "Head_of_Department"),
                            (3, "Advisor"),
                            (4, "Associate_Dean"),
                            (5, "Scholarship"),
                            (6, "Sponsorship"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseApplication",
            fields=[
                (
                    "course_application_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "course_code",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "course_title",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("course_credits", models.IntegerField(default=0)),
                ("aus_course", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "department",
                    models.IntegerField(
                        choices=[
                            (0, "Unknown"),
                            (1, "Architecture"),
                            (2, "Art and Design"),
                            (3, "Arabic and Translation Studies"),
                            (4, "Biology, Chemistry and Environmental Sciences"),
                            (5, "English"),
                            (6, "International Studies"),
                            (7, "Media Communication"),
                            (8, "Mathematics and Statistics"),
                            (9, "Physics"),
                            (10, "Psychology"),
                            (11, "Chemical and Biological Engineering"),
                            (12, "Civil Engineering"),
                            (13, "Computer Science and Engineering"),
                            (14, "Electrical Engineering"),
                            (15, "Industrial Engineering"),
                            (16, "Mechanical Engineering"),
                            (17, "Accounting"),
                            (18, "Economics"),
                            (19, "Finance"),
                            (20, "Management, Strategy and Entrepreneurship"),
                            (21, "Marketing and Information Systems"),
                        ],
                        default=0,
                        null=True,
                    ),
                ),
                ("syllabus", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "aus_syllabus",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "program_area",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "grade_required",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("pre_requisites_met", models.BooleanField(blank=True, null=True)),
                ("approved_status", models.BooleanField(null=True)),
                ("comparison_result", models.JSONField(blank=True, null=True)),
                ("running_comparison", models.BooleanField(default=False)),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "delegated_to",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("delegated_approval", models.BooleanField(blank=True, null=True)),
                (
                    "force_approval_to",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "approved_by",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.student"
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.university",
                    ),
                ),
            ],
            options={
                "ordering": ["course_application_id"],
            },
        ),
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
