# Generated by Django 4.2.9 on 2024-05-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="form_comments",
            field=models.TextField(blank=True, null=True),
        ),
    ]
