# Generated by Django 4.2.9 on 2024-04-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="student_id",
        ),
        migrations.AddField(
            model_name="student",
            name="aus_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
