# Generated by Django 5.0.1 on 2024-03-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_university_alter_faculty_faculty_id_course_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseapplication',
            name='grade',
            field=models.CharField(max_length=3),
        ),
    ]
