# Generated by Django 4.2.9 on 2024-03-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_courseapplication_grade"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="student",
            name="last_name",
        ),
        migrations.AddField(
            model_name="student",
            name="current_standing",
            field=models.CharField(default="Freshman", max_length=20),
        ),
        migrations.AddField(
            model_name="student",
            name="major",
            field=models.CharField(default="Comp Science", max_length=20),
        ),
        migrations.AddField(
            model_name="student",
            name="name",
            field=models.CharField(default="ayah", max_length=40),
        ),
        migrations.AddField(
            model_name="student",
            name="present_college",
            field=models.CharField(default="CEN", max_length=20),
        ),
    ]
