# Generated by Django 4.2.9 on 2024-04-16 06:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_courseapplication_approved_status_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="courseapplication",
            options={"ordering": ["course_application_id"]},
        ),
    ]
