# Generated by Django 4.2.9 on 2024-03-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_remove_student_first_name_remove_student_last_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="current_standing",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="student",
            name="major",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="student",
            name="present_college",
            field=models.CharField(max_length=20),
        ),
    ]
