# Generated by Django 4.2.9 on 2024-03-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_student_current_standing_alter_student_major_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="current_standing",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="student",
            name="expected_graduation",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="student",
            name="major",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="student",
            name="present_college",
            field=models.CharField(max_length=50),
        ),
    ]
