# Generated by Django 4.2.9 on 2024-04-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_courseapplication_delegated_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseapplication",
            name="delegated_approval",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
