# Generated by Django 4.2.9 on 2024-04-25 04:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseapplication",
            name="comments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="faculty_type",
            field=models.PositiveIntegerField(
                choices=[
                    (0, "Admin_Assistant"),
                    (1, "Teaching_Faculty"),
                    (2, "Head_of_Department"),
                    (3, "Advisor"),
                    (4, "Associate_Dean"),
                    (5, "Scholarship"),
                    (6, "Sponsorship"),
                ],
                default=0,
            ),
        ),
    ]
