# Generated by Django 4.2.9 on 2024-04-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_courseapplication_comments_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseapplication",
            name="force_approval_to",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="courseapplication",
            name="delegated_to",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
