# Generated by Django 4.2.9 on 2024-04-26 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_courseapplication_force_approval_to_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IXODetails",
            fields=[
                (
                    "initial_approval_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("moe_approval", models.BooleanField(blank=True, null=True)),
                ("usdoe_approval", models.BooleanField(blank=True, null=True)),
                ("acreditted", models.BooleanField(blank=True, null=True)),
                ("acreditted_comments", models.TextField(blank=True, null=True)),
                ("agreement", models.BooleanField(blank=True, null=True)),
                ("initial_approval_date", models.DateField(blank=True, null=True)),
                (
                    "student_type",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("final_approval", models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="student",
            name="ixo_details",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.ixodetails",
            ),
        ),
    ]
