# Generated by Django 4.2.9 on 2024-04-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_ixodetails_student_ixo_details"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"ordering": ["aus_id"]},
        ),
        migrations.AlterField(
            model_name="student",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
