# Generated by Django 4.2.9 on 2024-04-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_alter_student_options_alter_student_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="submitted_form",
            field=models.BooleanField(default=False),
        ),
    ]
