# Generated by Django 4.2.9 on 2024-04-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0017_student_submitted_form"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseapplication",
            name="approved_by",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
